global:
  scrape_interval: 30s 

scrape_configs:
  - job_name: 'django'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['web:8000'] 

  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']